package com.github.tiwindetea.dungeonoflegend.events.living_entities;

/**
 * Created by Lucas on 21/05/2016.
 */
public enum LivingEntityEventType {
    LIVING_ENTITY_CREATION_EVENT,
    LIVING_ENTITY_DELETION_EVENT,
    LIVING_ENTITY_LOS_DEFINITION_EVENT,
    LIVING_ENTITY_LOS_MODIFICATION_EVENT,
    LIVING_ENTITY_MOVE_EVENT,
    LIVING_ENTITY_HEALTH_UPDATE_EVENT,
	LIVING_ENTITY_HEALTH_VISIBILITY_EVENT
}
